name: Test and Release

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: docker/scout-action@${{ github.head_ref }}
        with:
          command: quickview
          image: docker/scout-demo-service:main
      - uses: docker/scout-action@${{ github.head_ref }}
        with:
          command: cves
          image: docker/scout-demo-service:main
      - run: |
          docker pull docker/scout-demo-service:fix
      - uses: docker/scout-action@${{ github.head_ref }}
        with:
          command: compare
          image: registry://docker/scout-demo-service:main
          to: local://docker/scout-demo-service:fix
          exit-code: false

  release:
    if:  startsWith(github.head_ref, 'release/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Tag name
        uses: mad9000/actions-find-and-replace-string@2
        id: tagname
        with:
          source: ${{ github.head_ref }}
          find: 'release/'
          replace: ''
      - name: Merge and Tag
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git merge --ff-only origin/${{ github.head_ref }}
          git tag ${{ steps.tagname.outputs.value }}
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main --tags
